### ISSUE TITLE
Memory allocation crash with LONGTEXT columns on low-mem systems

### ISSUE THREAD

**Issue by vzsg** [vapor/mysql#103]
Today, a strange low-level crash was reported on Slack, starting from [here](https://qutheory.slackarchive.io/help/page-77), stacktrace [here](https://qutheory.slack.com/files/hrpedersen/F659UA744/bt_gives.txt).

I built a test case out of it: #102, which passes on CircleCI, but that is just a coincidence.

After some more discussion in DM, it seems that the crash is tied to the available virtual memory of the system: 
- The reporter's DigitalOcean droplet has 512 MB RAM and 2 GB swap.
- After increasing the swap to 5 GB on the droplet, the crash disappears.
- CircleCI has 4 GB RAM allocated for every builder VM, and the test doesn't crash.

My educated guess is that Bind tries to allocate ~Int32.max (2 GB) or a similar, huge block of memory~ UInt32.max (4294967295 bytes), that fails without enough virtual memory available.

**Comment by vzsg** [comment]
Update:

I have managed to reproduce the issue in Docker and `ulimit -Sv 512000`. The same stacktrace is shown in the core dump.

After adding a simple print to Bind.swift to see the amount of allocated bytes, my suspicion is confirmed:

```
Trying to allocate: 4294967295
```

**Comment by tanner0101** [comment]
Thanks for the bug report test case!

It looks like if we simply use `max_length` instead of `length` on the `MYSQL_FIELD` struct we would only need to allocate enough memory to hold the largest value actually in the result set (not just the largest value _possible_).

We're currently using [`length`](https://github.com/vapor/mysql/blob/master/Sources/MySQL/Bind/Bind.swift#L59)

> The server determines the length value before it generates the result set, so this is the minimum length required for a data type capable of holding the largest possible value from the result column, without knowing in advance the actual values that will be produced by the query for the result set.

We should use `max_length`.

> The maximum width of the field for the result set (the length in bytes of the longest field value for the rows actually in the result set).

There's a concerning note later:

> If you are using prepared statements, max_length is not set by default

But it looks like we might be able to work around that.

**Comment by vzsg** [comment]
I hope working around is really possible, I didn't read the docs, but observed `max_length` being always 0.

**Comment by vzsg** [comment]
Apparently, [there's a flag for that](https://dev.mysql.com/doc/refman/5.7/en/mysql-stmt-attr-set.html)

**Comment by tanner0101** [comment]
Really strange that they would hide `max_length` behind a flag when that really seems like what people should be using to prevent extraneous memory allocation... Makes me wonder what other applications are using.

I'll take a stab at implementing this today and see if it works.
