### ISSUE TITLE
mysql build issue

### ISSUE THREAD

**Issue by rrvemula** [vapor/mysql#105]
Hi,

I installed MySQL manually and the location is /usr/local/mysql and underneath this location I have the following directories - bin, lib, man etc directories

I've included .Package(url: "https://github.com/vapor/mysql-provider.git", majorVersion: 2) in Package.swift 

I tried compiling vapor build --clean and get the following error
Fetching Dependencies [                        •]
Error: backgroundExecute(code: 1, error: "swift-package: error: /Users/rrvemula/Documents/Development/Hello/Package.swift:10:9: error: \'(arrayLiteral: Package.Dependency, _)\' is not convertible to \'(arrayLiteral: Package.Dependency...)\', tuples have a different number of elements\n        .Package(url: \"https://github.com/vapor/vapor.git\", majorVersion: 2),\n        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\nexit(1): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc --driver-mode=swift -I /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/pm -L /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/pm -lPackageDescription -target x86_64-apple-macosx10.10 /Users/rrvemula/Documents/Development/Hello/Package.swift -fileno 11\n", output: "")

I also tried vapor xcode and get the following error
Generating Xcode Project [Failed]
swift-package: error: /Users/rrvemula/Documents/Development/Hello/Package.swift:10:9: error: '(arrayLiteral: Package.Dependency, _)' is not convertible to '(arrayLiteral: Package.Dependency...)', tuples have a different number of elements
        .Package(url: "https://github.com/vapor/vapor.git", majorVersion: 2),
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
exit(1): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc --driver-mode=swift -I /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/pm -L /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/pm -lPackageDescription -target x86_64-apple-macosx10.10 /Users/rrvemula/Documents/Development/Hello/Package.swift -fileno 11

Error: Could not generate Xcode project: swift-package: error: /Users/rrvemula/Documents/Development/Hello/Package.swift:10:9: error: '(arrayLiteral: Package.Dependency, _)' is not convertible to '(arrayLiteral: Package.Dependency...)', tuples have a different number of elements
        .Package(url: "https://github.com/vapor/vapor.git", majorVersion: 2),
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
exit(1): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc --driver-mode=swift -I /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/pm -L /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/pm -lPackageDescription -target x86_64-apple-macosx10.10 /Users/rrvemula/Documents/Development/Hello/Package.swift -fileno 11

can someone please help me wit resolving this?

I looked up other issues logged (#29, #67 )but was unable to resolve it.

**Comment by vzsg** [comment]
This doesn't seem to be related to the mysql package, but most likely a syntax error in your Package.swift file. It's actually pretty clearly visible if you read the output.

Perhaps you didn't add a comma after the vapor.git dependency?

**Comment by rrvemula** [comment]
Thanks @vzsg - My bad. it was a comma after the git dependency
