### ISSUE TITLE
Crashes on ubuntu 16.04.3

### ISSUE THREAD

**Issue by MihaelIsaev** [vapor/mysql#121]
I'm trying to run standart Todo project with fluentmysql on Ubuntu 16.0.4 and it crashes with error `Fatal error: ⚠️ [TCP.TCPError.read: Bad file descriptor] [/services/todo2/.build/checkouts/sockets.git-8311360091744607488/Sources/TCP/Socket/TCPSocket.swift:106:37] : file /services/todo2/.build/checkouts/sockets.git-8311360091744607488/Sources/TCP/Streams/TCPSocketSink.swift, line 68`

<img width="993" alt="2018-02-02 4 30 21" src="https://user-images.githubusercontent.com/1272610/35710596-d2bf3ca0-07d1-11e8-951c-e70476854a68.png">

[todo-mysql-with_null.zip](https://github.com/vapor/mysql/files/1687676/todo-mysql-with_null.zip)

##Environment

MySQL: Ver 14.14 Distrib 5.7.21, for Linux (x86_64)
Vapor: 3 beta
Swift: 4.1 dev

**Comment by tanner0101** [comment]
This error was fixed in the TCP package (related to the socket being closed)
