### ISSUE TITLE
Incorrect tagging, unable to build with the V3 beta

### ISSUE THREAD

**Issue by SandorDobi** [vapor/mysql#125]
The repo have an incorrect tagging.
The master branch is tagged for the latest beta tag, that tag is about 2 month old commit. 
the fluent-mysql dependecy will pull in this version, which cannot be build with the rest V3 betas.
Please remove this tag and tag the latest beta commit.

Regards

**Comment by 0xTim** [comment]
Should be fixed with https://github.com/vapor/mysql/releases/tag/3.0.0-beta.4
