### ISSUE TITLE
Error when using localhost as host to server connect   

### ISSUE THREAD

**Issue by ditansu** [vapor/mysql#149]
This code 
```swift
let databaseConfig = MySQLDatabaseConfig(
    hostname: "localhost",
    port: 3306,
    username: "test",
    password: "test", 
    database: "test") 
  services.register(databaseConfig)
```
raise the exception: 
```
[MySQL] read(descriptor:pointer:size:) failed: Connection refused (errno: 61) 
```
If change `localhost` to `127.0.0.1` all work is correctly 

```swift
let databaseConfig = MySQLDatabaseConfig(
    hostname: "127.0.0.1",
    port: 3306,
    username: "test",
    password: "test", 
    database: "test") 
  services.register(databaseConfig)
```
output:
```
Migrating mysql DB
Migrations complete
Server starting on http://localhost:8080
```

**Comment by twof** [comment]
Also experiencing this, but it didn't seem to cause any problems with querying or whatever

**Comment by ditansu** [comment]
>Also experiencing this, but it didn't seem to cause any problems with querying or whatever

I also do not see much trouble in this, but this is a very frustrating and confusing situation for (new) users (I've spent 1,5 hour to find solution). Moreover, in the official documentation it is written that it is necessary to use the `localhost`  also `MySQLDatabaseConfig.root(database: String)` use localhost and therefore don't works too. 

In any case it's not good when our system behaves not so we expect and we don't know why this happens. Especially since the root problem seems to be at level of NIO.

**Comment by tanner0101** [comment]
I'll swap this to using 127.0.0.1 👍
