### ISSUE TITLE
mysql pooled connection error

### ISSUE THREAD

**Issue by britchiex** [vapor/mysql#154]
this example route from the 3.0-rc documentation (https://docs.vapor.codes/3.0/mysql/core/#query) will not compile

```router.get("mysql-version") { req -> Future<String> in
    return req.withPooledConnection(to: .mysql) { conn in
        return try conn.query("select @@version as v;").map(to: String.self) { rows in
            return try rows[0].firstValue(forColumn: "v")?.decode(String.self) ?? "n/a"
        }
    }
}
```  

xcode complains with the error `Member 'mysql' in 'DatabaseIdentifier<_>' produces result of type 'DatabaseIdentifier<MySQLDatabase>', but context expects 'DatabaseIdentifier<_>'`

**Comment by tomcomer** [comment]
I was having this issue too. It seems you have to be a little more specific to help out the compiler:

`return req.withPooledConnection(to: .mysql) { (conn: MySQLDatabase.Connection) in
    return conn.simpleQuery("select @@version as v").map(to: String.self) { rows in
        return try rows[0].firstValue(forColumn: "v")?.decode(String.self) ?? "n/a"
    }
}`

Once I did that, it worked as expected.

**Comment by tanner0101** [comment]
I'll make sure this gets fixed in the docs, thanks!
