### ISSUE TITLE
mysql request timed out but still posting

### ISSUE THREAD

**Issue by stvnmcdonald** [vapor/mysql#157]
Whenever I use a POST or GET with MySQL, the request always times out before routing to another view or posting data, but it successfully routes and posts to the DB. I have tried multiple versions of MySQL (5.6 and 5.7), multiple MySQL configurations environments (Docker, MAMP,  Local install, dedicated Linux remote install) and I get the same result.
Currently using MySQL 5.7.21 on a dedicated Linux VM. Running Vapor on Mac OSX.
Packages:
```
   .package(url: "https://github.com/vapor/vapor.git", from: "3.0.0-rc"),
        .package(url: "https://github.com/vapor/fluent-mysql.git", from: "3.0.0-rc.2.3"),
        .package(url: "https://github.com/vapor/leaf.git", from: "3.0.0-rc"),
        .package(url: "https://github.com/vapor/auth.git", from: "2.0.0-rc")
```
POST func
```
  func createHandler(_ req: Request) throws -> Future<User> {
        return try req.content.decode(User.self).flatMap(to: User.self) { user in
        let hasher = try req.make(BCryptDigest.self)
        user.password = try String.convertFromData(hasher.hash(user.password))
        return user.save(on: req)
        }
    }
```

**Comment by mcdappdev** [comment]
I've had some weird timeouts on `BCrypt` as well. Not sure if it's related or not

**Comment by stvnmcdonald** [comment]
This isn't related to MySQL. Closing.
