### ISSUE TITLE
MySQLError.basicPacket: Unrecognized basic packet

### ISSUE THREAD

**Issue by mcdappdev** [vapor/mysql#158]
I get this error when running the app. Everything else works fine, but it looks like maybe it’s misinterpreting an OK signal. MySQL version 5.7.18. I sent query logs to Tanner privately.

**Comment by jseibert** [comment]
I see this as well and haven't had time to dive in yet. But I can confirm it's not specific to your setup :)

**Comment by tanner0101** [comment]
This was fixed a while back. Thanks @mcdappdev!
