### ISSUE TITLE
Error using MariaDB

### ISSUE THREAD

**Issue by DavidBrunow** [vapor/mysql#162]
When running the latest RC of Vapor 3 with a MariaDB database the assertion on line 72 of MySQLHandshakeV10.swift fails.

The value of `reserved` is `[0, 0, 0, 0, 0, 0, 7, 0, 0, 0]` rather than the asserted value of all zeros.

**Comment by tholo** [comment]
This is addressed in #174 -- would be nice if we could get a new RC with at least this in. That way we can use MariaDB in debug mode...

**Comment by tanner0101** [comment]
This package is now tested against MariaDB 10.3: https://github.com/vapor/mysql/pull/176/commits/d08732b9ec22dd4ea4b85057ee5d038008f30222
