### ISSUE TITLE
Support for latest MySQL

### ISSUE THREAD

**Issue by 0xTim** [vapor/mysql#172]
MySQL 10.something has broken support for Vapor due to the SHA2 auth requirements. This should be fixed!

**Comment by gazingatnavel** [comment]
In Vapor MySQL version 3.0.0-rc2.2, fIle [MySQLConnection+Authenticate.swift](https://github.com/vapor/mysql/blob/master/Sources/MySQL/Connection/MySQLConnection%2BAuthenticate.swift):
```swift
 4: extension MySQLConnection {
    ...
12:    public func authenticate(username: String, database: String, password: String? = nil) -> Future<Void> {
       ...
27:        switch authPlugin {
28:        case .some("mysql_native_password"), .none:
           ...
```
From this [MySQL Server Blog post](http://mysqlserverteam.com/mysql-8-0-4-new-default-authentication-plugin-caching_sha2_password/), starting with MySQL version 8.0.4, the default authentication plugin is `caching_sha2_password`.

This case is not handled in the MySQLConnection+Authenticate.swift code, causing an authentication error when attempting to connect to a MySQL database that uses the default authentication plugin of `caching_sha2_password`.

I encountered this error while connecting to a MySQL database in a Docker container for testing on my local machine. (Note that connecting to a Vapor Cloud MySQL database server did not encounter this error.)

There are workarounds, of course, such as using an earlier version of MySQL that uses the default authentication plugin of `mysql_native_password`, or including the option [`--default-authentication-plugin=mysql_native_password`](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_default_authentication_plugin).

The case `caching_sha2_password` should be handled in the Vapor MySQLConnection+Authenticate.swift code to enable the default authentication plugin for the latest versions of MySQL.

**Comment by tanner0101** [comment]
Support for `caching_sha2_password` over _TLS_ has been added here  https://github.com/vapor/mysql/pull/176. Doing it over cleartext is much more involved and should be a separate issue.

**Comment by tanner0101** [comment]
Feel free to open a request for 8.0 `caching_sha2_password ` cleartext support if that's something that should be supported. (From what I can tell, no one is really using that).
