### ISSUE TITLE
MySQL driver discards "afffected rows" data from COM_EXECUTE replies

### ISSUE THREAD

**Issue by 0xTim** [vapor/mysql#173]
In the binary protocol, MySQL returns the "affected rows" value (number of rows in result for DQL, number of rows inserted/updated/deleted for DML) in the first OK packet's affected_rows field. The MySQL driver currently decodes this field, but the OK packet is discarded by MySQLConnection._query()'s state machine. This value should be preserved for higher-level API, as having that information is critical to implementing efficient concurrency-safe algorithms using MySQL.

**Comment by tanner0101** [comment]
This will be available in `conn.lastMetadata` for 3.0.0.

**Comment by tanner0101** [comment]
(Related to #176)
