### ISSUE TITLE
HandshakeV10 packet Ignored

### ISSUE THREAD

**Issue by rb-de0** [vapor/mysql#175]
A handshakeV10 packet is ignored rarely  when creating a new connection using ```newConnection ``` method.

After connecting to MySQL Server, it seems that ```channelRead``` method in QueueHandler is called before adding handshake callback.

## Environment
OS: Ubuntu 16.04
MySQL Server: mysql  Ver 14.14 Distrib 5.7.22, for Linux (x86_64) using  EditLine wrapper
Frameworks: 
    - MySQL 3.0.0-rc.2.2,
    - Core 3.1.7

## Log
`
[WARNING] [Async] [QueueHandler] Read triggered when input queue was empty, ignoring: handshakev10(MySQL.MySQLHandshakeV10(protocolVersion: 10, serverVersion: "5.7.22-0ubuntu0.16.04.1", connectionID: 8, authPluginData: 21 bytes, capabilities: CLIENT_NO_SCHEMA | CLIENT_PLUGIN_AUTH | CLIENT_CONNECT_ATTRS | CLIENT_CAN_HANDLE_EXPIRED_PASSWORDS | CLIENT_CONNECT_WITH_DB | CLIENT_PROTOCOL_41 | CLIENT_COMPRESS | CLIENT_FOUND_ROWS | CLIENT_LONG_FLAG | CLIENT_ODBC | CLIENT_IGNORE_SPACE | CLIENT_MULTI_STATEMENTS | CLIENT_INTERACTIVE | CLIENT_LOCAL_FILES | CLIENT_PS_MULTI_RESULTS | CLIENT_IGNORE_SIGPIPE | CLIENT_MULTI_RESULTS | CLIENT_SESSION_TRACK | CLIENT_RESERVED | CLIENT_PLUGIN_AUTH_LENENC_CLIENT_DATA | CLIENT_TRANSACTIONS | CLIENT_DEPRECATE_EOF | CLIENT_LONG_PASSWORD | CLIENT_SECURE_CONNECTION, characterSet: Optional(latin1_swedish_ci), statusFlags: Optional(2), authPluginName: Optional("mysql_native_password"))).
`

**Comment by tanner0101** [comment]
I have also noticed this happening. I will dig into this, thanks!

**Comment by tanner0101** [comment]
`QueueHandler` is no longer being used. See #176.
