### ISSUE TITLE
MySQLTime should provide a more concise description

### ISSUE THREAD

**Issue by 0xTim** [vapor/mysql#218]
When converted to `String` via `.description`, `MySQLTime` gets the default description generated via `Mirror`, which looks like this: `MySQL.MySQLTime(year: 2018, month: 11, day: 26, hour: 4, minute: 19, second: 24, microsecond: 955255)`. This is considerably more verbose than it really needs to be under most circumstances and makes the values provided in e.g. a `DatabaseLog` more difficult to work with visually. Since `MySQLTime` is internal to the `mysql` module, consumers of the driver can't add their own `CustomStringConvertible` or `CustomDebugStringConvertible` conformances to the type. `MySQLTime` should either provide `description` and/or `debugDescription` as e.g. `return (try? Date.convertFromMySQLTime(self)).description ?? "<error>"` or be marked `public` so apps can provide their own conformances or other mechanisms.

**Comment by tanner0101** [comment]
@0xTim LMK what you think of the fix in #222. It's a pseudo RFC 3339 format that doesn't require converting to/from `Swift.Date`.
