### ISSUE TITLE
"Fatal error: Unexpected packet" when decoding key case does not match

### ISSUE THREAD

**Issue by eneko** [vapor/mysql#223]
This error took me a while to figure out. The actually issue was on my end. I was doing a raw query for a field `driverref` when the `Codable` data structure receiving values had a `let driverRef: String` property. Note the difference between camel case and lowercase.

I decided to share it here to help other users that might be having the same issue, but also, in case there is a way to provide a better error message output, something like `missing coding key` or similar. I've looked at the code throwing this error, but didn't have a good idea on how to improve it.

```
[mysql] [2018-12-17 16:02:12 +0000]     select driverref, forename as firstname
      from gps_seasondrivers
     where year = ?
     order by points desc, wins desc, position2 desc, position3 desc,
           position4 desc, position5 desc, position6 desc, surname [integer8(1950)]
Fatal error: Unexpected packet: binaryResultsetRow(MySQL.MySQLBinaryResultsetRow(values: [MySQL.MySQLBinaryData(type: MYSQL_TYPE_VAR_STRING, isUnsigned: false, storage: MySQL.MySQLBinaryDataStorage.string(7 bytes)), MySQL.MySQLBinaryData(type: MYSQL_TYPE_VAR_STRING, isUnsigned: false, storage: MySQL.MySQLBinaryDataStorage.string(5 bytes))]))
```

**Comment by calebkleveter** [comment]
I created an example project that displays this problem. If you run the `GET /mysql-crash` route, you'll get the error.

https://github.com/calebkleveter/FluentMySQLCrash

**Comment by eneko** [comment]
Thank you, guys!
