### ISSUE TITLE
Doesn't work with latest MySQL (8.0.13)

### ISSUE THREAD

**Issue by marekpridal** [vapor/mysql#225]
Vapor seems to doesn't work with latest MySQL version (8.0.13). Downgrade to version 5.7 solved issue. On running with higher version, Vapor on start throws error. 

```
id: MySQLError.basicPacket
```

More discussed in `#vapor-3` channel in Discord.

**Comment by eneko** [comment]
@marekpridal Please see https://github.com/vapor/mysql/issues/193 for guidance on how to solve this issue. MySQL 8.0 introduces a new method for password encoding and it seems Vapor only supports the new method: https://github.com/vapor/mysql/issues/193
