### ISSUE TITLE
is it possible to use this mySQL wrapper in iPhone application? 

### ISSUE THREAD

**Issue by faklyasgyuri** [vapor/mysql#26]
Hi!
I dealed some time with vapor, spm and these stuffs which are new for me, but I think first I had to ask this question. Can I remote mySQL database from iPhone app with this wrapper or is it just for Desktop applications? Because I've read about this on many sites, that connect to a MySQL database with iPhone it's not safe, and not recommended, and everyone recommend to write php scripts to remote mySQL database... Thank you for your answer and help.

**Comment by tannernelson** [comment]
I don't know for sure, but my assumption would be that Apple would reject an app that links `libmysqlclient` if it were even possible. What you want to do here is something similar to `vapor/university` (you should check that repo out!).

Basically, you create the following packages:

- Package Server/API (MySQL): Returns data from MySQL as JSON
- Package Client: Accepts JSON API and converts to Models
    - Web: Converts Models into HTML
    - iOS: Converts Models into UIViewControllers and UIViews

So here you have two separate packages, Server and Client.

The Client then has three modules. A generic JSON parsing module and then two modules for front ends. An iOS and a Web frontend.

This way you aren't linking `libmysqlclient` to iOS. You are linking a library that parses the JSON from your API that uses `libmysqlclient`.
