### ISSUE TITLE
MySQL Fluent Driver not returning elements

### ISSUE THREAD

**Issue by vdka** [vapor/mysql#28]
```swift
print(try mysql.driver.raw("SELECT * FROM users")) // 1 element
print(try User.all()) // []
```
where the DB is defined with
```swift
// ...
  static func prepare(_ database: Database) throws {
    try database.create("users") {
      $0.id()
      $0.string("name")
      $0.string("email")
      $0.string("hash")
    }
  }
// ...
```

`Package.swift`
```
  dependencies: [
    .Package(url: "https://github.com/vapor/vapor.git", majorVersion: 0, minor: 16),
    .Package(url: "https://github.com/vapor/vapor-mysql.git", majorVersion: 0, minor: 4),
  ],
```

**Comment by tannernelson** [comment]
Try 
```swift
User.database = mysql
```

This should happen automatically if you're passing the `User` as a preparation.

**Comment by vdka** [comment]
I think maybe I am using the Provider correctly.

```swift
import HTTP
import Vapor
import VaporMySQL

let mysql = try VaporMySQL.Provider(host: "localhost", user: "root", password: "", database: "tappr")

let drop = Droplet(preparations: [Product.self, User.self], initializedProviders: [mysql])

// per your suggestion
User.database = mysql // error: Cannot assign value of type 'Provider' to type 'Database?'
```

**Comment by tannernelson** [comment]
```swift
User.database = mysql.database
```

But looks like your other code is correct. Are any error messages being printed out? It's likely that the user isn't able to be initialized because of missing values in the table.

**Comment by vdka** [comment]
```
error: value of type 'Provider' has no member 'database'
User.database = mysql.database
                ^~~~~ ~~~~~~~~
```
😕 
I am definitely supposed to use `vapor-mysql` not anything else?

**Comment by tannernelson** [comment]
`vapor-mysql` should be `mysql-provider`.

This has some more information about the difference between providers and drivers: https://vapor.github.io/documentation/fluent/driver.html

Skip the `User.database = ` part. I'm pretty sure what's happening here is somehow User is not getting all the data it needs to initialize so it's getting skipped.

https://github.com/vapor/fluent/blob/master/Sources/Fluent/Query/Query.swift#L99

You can see that if the init throws an error (one of the `extract()` calls failed), the row is skipped.

**Comment by vdka** [comment]
Alright, worked it out, it was user error. Being Stringly typed in places hurts.
