### ISSUE TITLE
TINYINT Issues

### ISSUE THREAD

**Issue by collinhundley** [vapor/mysql#31]
MySQL `TINYINT` fields still aren't being handled correctly on Linux.

Example: My table has a `TINYINT` column, and so I store a value of `2` in it.  When I perform a fetch using this package, I extract the field like this:

```swift
let myField = result["myCol"]!.int  // myField is an `Int` 
```

On macOS, `myField` now has a value of `2`. On Linux, `myField` has a value of `140533208973314`.

Any ideas of what might be going on?

**Comment by collinhundley** [comment]
Ok, now I'm seriously confused... the same value doesn't even get returned every time.

I fetch once, and `myField` = `140533208973314`. I fetch again immediately afterward, and `myField` = `140533141864450`. I fetch again, and it's back to `140533208973314`.

It alternates back and forth between those two values with each fetch. What's more, those values change if I restart the application. But always alternating between two large numbers... no joke.

**Comment by tannernelson** [comment]
Not surprising haha, looks like it's just reading from the wrong memory. Could you submit a bug PR with a failing test case? Or at least how to recreate the bug?

It's probably an easy fix.

**Comment by collinhundley** [comment]
I spent a little time digging into it, but I haven't pinpointed the problem yet. The only potential issue I've found is during the initialization of `Bind` for the output binds. In `Bind.swift`:

```swift
var cBind = CBind()
cBind.buffer_type = field.cField.type
let length = Int(field.cField.length)
cBind.buffer_length = UInt(length)
cBind.buffer = UnsafeMutablePointer<Void>.allocate(capacity: length)
```

Here, when `buffer_type` is `MYSQL_TYPE_TINY`, `length` returns 4. My understanding of `TINYINT

**Comment by tannernelson** [comment]
According to the docs ```TINYINT	MYSQL_TYPE_TINY	signed char```

So it looks like you're right, it's 1 byte. The `length` value could be a garbage value coming from a previous query or column.

**Comment by collinhundley** [comment]
Strangely enough, I can't seem to reproduce how I got 4 bytes for `length`. I'm testing it again and I get 3 bytes every time on Linux and macOS. Maybe I just misread/mistyped it earlier.

Either way, 3 bytes seems strange for a value that should only use 1. However, I should point out that `length` is also 3 on macOS (where this problem doesn't occur at all), so it's possible that `length` isn't even the issue.

**Comment by tannernelson** [comment]
I'm almost 99% sure `length` shouldn't be used for TINYINT. So it's just pointing at garbage data or data from some previous operation. I think for TINYINT we must assume a length of 1.

**Comment by collinhundley** [comment]
I think I found our problem. In `Bind+Node.swift`, in the getter for `value`:

```swift
func unwrap<T>(_ buffer: UnsafeMutablePointer<Void>, _ type: T.Type) -> T {
    return UnsafeMutablePointer<T>(buffer).pointee
}
...
case MYSQL_TYPE_TINY:
    if cBind.is_unsigned == 1 {
        let uint = unwrap(buffer, UInt.self)
        return .number(.uint(UInt(uint)))
    } else {
        let int = unwrap(buffer, Int.self)
        return .number(.int(Int(int)))
    }
```

We're initializing a 64-bit pointer (`Uint`/`Int`), but `buffer` isn't large enough to fill the space. So we're left with junk. Changing those lines to

`let uint = unwrap(buffer, UInt8.self)`

and 

`let int = unwrap(buffer, Int8.self)`

solves everything.

**Comment by collinhundley** [comment]
What I'd love to know is why I only experienced this problem on Linux.

I guess it's possible that the extra memory just happened to be zeroed out on my Mac, but I doubt it.
