### ISSUE TITLE
MySQL build error

### ISSUE THREAD

**Issue by Shunzi007** [vapor/mysql#35]
## My Package file:

> import PackageDescription
> 
> let package = Package(
>     name: "WelcomAPI",
>     dependencies: [
>         .Package(url: "https://github.com/vapor/vapor.git", majorVersion: 0, minor: 16),
>         .Package(url: "https://github.com/vapor/vapor-mustache.git", majorVersion: 0, minor: 11),
>         .Package(url: "https://github.com/vapor/vapor-mysql.git", majorVersion: 0, minor: 4)
>     ],
>     exclude: [
>         "Config",
>         "Database",
>         "Localization",
>         "Public",
>         "Resources",
>         "Tests",
>     ]
> )

## When run "vapor build", it tells:

> Fetching Dependencies [Done]
> Building Project [Failed]
> 
> Command:
> swift build 1>&2
> 
> Error (1):
> Compile Swift Module 'SocksCore' (14 sources)
> Compile Swift Module 'libc' (1 sources)
> Compile Swift Module 'CryptoEssentials' (15 sources)
> Compile Swift Module 'Polymorphic' (2 sources)
> Compile Swift Module 'Strand' (1 sources)
> Compile Swift Module 'Mustache' (29 sources)
> Compile Swift Module 'PathIndexable' (2 sources)
> Compile Swift Module 'Node' (21 sources)
> Compile Swift Module 'Fluent' (29 sources)
> Compile Swift Module 'Core' (22 sources)
> Compile Swift Module 'Socks' (5 sources)
> Compile Swift Module 'SocksCoreExampleTCPServer' (1 sources)
> Compile Swift Module 'SocksCoreExampleTCPClient' (1 sources)
> /Users/h172462/Desktop/AppDemo/WelcomeAPI/Packages/Mustache-0.0.0/Sources/Mustache/Rendering/Context.swift:101:5: warning: 'warn_unused_result' attribute behavior is now the default
>     @warn_unused_result(message: "Context.extendedContext returns a new Context.")
>     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     
> /Users/h172462/Desktop/AppDemo/WelcomeAPI/Packages/Mustache-0.0.0/Sources/Mustache/Rendering/Context.swift:114:5: warning: 'warn_unused_result' attribute behavior is now the default
>     @warn_unused_result(message: "Context.contextWithRegisteredKey returns a new Context.")
>     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     
> Compile Swift Module 'SocksExampleUDPServer' (1 sources)
> Compile Swift Module 'SocksExampleUDPClient' (1 sources)
> Compile Swift Module 'SocksExampleTCPServer' (1 sources)
> Compile Swift Module 'SocksExampleTCPClient' (1 sources)
> Compile Swift Module 'SocksCoreExampleTCPKeepAliveServer' (1 sources)
> Linking ./.build/debug/SocksCoreExampleTCPClient
> Linking ./.build/debug/SocksCoreExampleTCPServer
> Linking ./.build/debug/SocksExampleUDPClient
> Linking ./.build/debug/SocksExampleTCPClient
> Linking ./.build/debug/SocksExampleUDPServer
> Linking ./.build/debug/SocksExampleTCPServer
> Linking ./.build/debug/SocksCoreExampleTCPKeepAliveServer
> Compile Swift Module 'SHA1' (1 sources)
> Compile Swift Module 'SHA2' (1 sources)
> Compile Swift Module 'HMAC' (1 sources)
> Compile Swift Module 'Console' (34 sources)
> Compile Swift Module 'JSON' (7 sources)
> Compile Swift Module 'MySQL' (9 sources)
> <module-includes>:1:9: note: in file included from <module-includes>:1:
> #import "/usr/local/include/mysql/mysql.h"
>         ^
> /usr/local/include/mysql/mysql.h:64:10: note: in file included from /usr/local/include/mysql/mysql.h:64:
> #include "mysql/client_plugin.h"
>          ^
> /usr/local/include/mysql/mysql/client_plugin.h:103:10: error: 'mysql/plugin_auth_common.h' file not found
> #include <mysql/plugin_auth_common.h>
>          ^
> /Users/h172462/Desktop/AppDemo/WelcomeAPI/Packages/MySQL-0.4.0/Sources/MySQL/Bind+Node.swift:4:12: error: could not build Objective-C module 'CMySQLMac'
>     import CMySQLMac
>            ^
> <module-includes>:1:9: note: in file included from <module-includes>:1:
> #import "/usr/local/include/mysql/mysql.h"
>         ^
> /usr/local/include/mysql/mysql.h:64:10: note: in file included from /usr/local/include/mysql/mysql.h:64:
> #include "mysql/client_plugin.h"
>          ^
> /usr/local/include/mysql/mysql/client_plugin.h:103:10: error: 'mysql/plugin_auth_common.h' file not found
> #include <mysql/plugin_auth_common.h>
>          ^
> /Users/h172462/Desktop/AppDemo/WelcomeAPI/Packages/MySQL-0.4.0/Sources/MySQL/Bind+Node.swift:4:12: error: could not build Objective-C module 'CMySQLMac'
>     import CMySQLMac
>            ^
> <module-includes>:1:9: note: in file included from <module-includes>:1:
> #import "/usr/local/include/mysql/mysql.h"
>         ^
> /usr/local/include/mysql/mysql.h:64:10: note: in file included from /usr/local/include/mysql/mysql.h:64:
> #include "mysql/client_plugin.h"
>          ^
> /usr/local/include/mysql/mysql/client_plugin.h:103:10: error: 'mysql/plugin_auth_common.h' file not found
> #include <mysql/plugin_auth_common.h>
>          ^
> /Users/h172462/Desktop/AppDemo/WelcomeAPI/Packages/MySQL-0.4.0/Sources/MySQL/Bind+Node.swift:4:12: error: could not build Objective-C module 'CMySQLMac'
>     import CMySQLMac
>            ^
> <module-includes>:1:9: note: in file included from <module-includes>:1:
> #import "/usr/local/include/mysql/mysql.h"
>         ^
> /usr/local/include/mysql/mysql.h:64:10: note: in file included from /usr/local/include/mysql/mysql.h:64:
> #include "mysql/client_plugin.h"
>          ^
> /usr/local/include/mysql/mysql/client_plugin.h:103:10: error: 'mysql/plugin_auth_common.h' file not found
> #include <mysql/plugin_auth_common.h>
>          ^
> /Users/h172462/Desktop/AppDemo/WelcomeAPI/Packages/MySQL-0.4.0/Sources/MySQL/Bind+Node.swift:4:12: error: could not build Objective-C module 'CMySQLMac'
>     import CMySQLMac
>            ^
> <module-includes>:1:9: note: in file included from <module-includes>:1:
> #import "/usr/local/include/mysql/mysql.h"
>         ^
> /usr/local/include/mysql/mysql.h:64:10: note: in file included from /usr/local/include/mysql/mysql.h:64:
> #include "mysql/client_plugin.h"
>          ^
> /usr/local/include/mysql/mysql/client_plugin.h:103:10: error: 'mysql/plugin_auth_common.h' file not found
> #include <mysql/plugin_auth_common.h>
>          ^
> /Users/h172462/Desktop/AppDemo/WelcomeAPI/Packages/MySQL-0.4.0/Sources/MySQL/Bind+Node.swift:4:12: error: could not build Objective-C module 'CMySQLMac'
>     import CMySQLMac
>            ^
> <module-includes>:1:9: note: in file included from <module-includes>:1:
> #import "/usr/local/include/mysql/mysql.h"
>         ^
> /usr/local/include/mysql/mysql.h:64:10: note: in file included from /usr/local/include/mysql/mysql.h:64:
> #include "mysql/client_plugin.h"
>          ^
> /usr/local/include/mysql/mysql/client_plugin.h:103:10: error: 'mysql/plugin_auth_common.h' file not found
> #include <mysql/plugin_auth_common.h>
>          ^
> /Users/h172462/Desktop/AppDemo/WelcomeAPI/Packages/MySQL-0.4.0/Sources/MySQL/Bind+Node.swift:4:12: error: could not build Objective-C module 'CMySQLMac'
>     import CMySQLMac
>            ^
> <module-includes>:1:9: note: in file included from <module-includes>:1:
> #import "/usr/local/include/mysql/mysql.h"
>         ^
> /usr/local/include/mysql/mysql.h:64:10: note: in file included from /usr/local/include/mysql/mysql.h:64:
> #include "mysql/client_plugin.h"
>          ^
> /usr/local/include/mysql/mysql/client_plugin.h:103:10: error: 'mysql/plugin_auth_common.h' file not found
> #include <mysql/plugin_auth_common.h>
>          ^
> /Users/h172462/Desktop/AppDemo/WelcomeAPI/Packages/MySQL-0.4.0/Sources/MySQL/Bind+Node.swift:4:12: error: could not build Objective-C module 'CMySQLMac'
>     import CMySQLMac
>            ^
> <module-includes>:1:9: note: in file included from <module-includes>:1:
> #import "/usr/local/include/mysql/mysql.h"
>         ^
> /usr/local/include/mysql/mysql.h:64:10: note: in file included from /usr/local/include/mysql/mysql.h:64:
> #include "mysql/client_plugin.h"
>          ^
> /usr/local/include/mysql/mysql/client_plugin.h:103:10: error: 'mysql/plugin_auth_common.h' file not found
> #include <mysql/plugin_auth_common.h>
>          ^
> /Users/h172462/Desktop/AppDemo/WelcomeAPI/Packages/MySQL-0.4.0/Sources/MySQL/Bind+Node.swift:4:12: error: could not build Objective-C module 'CMySQLMac'
>     import CMySQLMac
>            ^
> <unknown>:0: error: build had 1 command failures
> swift-build: error: exit(1): /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-07-25-a.xctoolchain/usr/bin/swift-build-tool -f /Users/h172462/Desktop/AppDemo/WelcomeAPI/.build/debug.yaml
> 
> Toolchain:
> /Users/h172462/.swiftenv/shims/swift
> 
> Help:
> Join our Slack where hundreds of contributors
> are waiting to help: http://slack.qutheory.io
> 
> Error: Build failed.

## And build by Xcode, it tells:

> /usr/local/include/mysql/mysql/client_plugin.h:103:10: 'mysql/plugin_auth_common.h' file not found
> /Users/h172462/Desktop/AppDemo/WelcomeAPI/Packages/MySQL-0.4.0/Sources/MySQL/Bind+Node.swift:4:12: Could not build Objective-C module 'CMySQLMac'

## could you help me to find out the cause?

**Comment by BrettRToomey** [comment]
`vapor build --mysql` on Mac to properly link libs.

**Comment by tannernelson** [comment]
This looks like an issue with the installation of MySQL with brew.
