### ISSUE TITLE
Fully qualified table names

### ISSUE THREAD

**Issue by bspringston** [vapor/mysql#5]
The table name used in the SQL statements needs to include the database name from the initialization settings.  For example, if the MySql database name is test, then select from users SQL statement would look like SELECT \* FROM test.users

**Comment by tannernelson** [comment]
Thanks for the feedback! This should be an easy change to make if you want to do the PR and be listed as a contributor.  

Otherwise I can get to it tomorrow. :)

**Comment by collinhundley** [comment]
Is this just a matter of preference? I'm using the table name alone in my statements and it works great.

**Comment by bspringston** [comment]
It matters when you have multiple schemas in MySQL.

**Comment by edwd** [comment]
As long as you are querying a table from the schema specified in the connection initialization, there should be no need to fully qualify the table name as you suggest. According to the documentation of the underlying MySQL API function used to create the connection (http://dev.mysql.com/doc/refman/5.7/en/mysql-real-connect.html):

 - `db` is the database name. If `db` is not `NULL`, the connection sets the default database to this value.

**Comment by BrettRToomey** [comment]
Closing this. Thanks @edwd
