### ISSUE TITLE
Connection pooling

### ISSUE THREAD

**Issue by collinhundley** [vapor/mysql#50]
@tannernelson mentioned a while ago that this package is only meant to be a simple Swift wrapper, but I'm wondering if you've had a change of heart.

It looks like thread safety has been implemented, so I think the next step would be to add connection pooling. We can reuse a single connection now but the server will usually drop it after a few hours, so we'll probably want to maintain a small pool of connections to recycle as they expire.

What do you guys think?

**Comment by tannernelson** [comment]
I wouldn't mind seeing this added. It could go on the `Database` class. The execution code moved to the `Connection` class which I think is a lot cleaner now. So users have the option to execute from `Database` in which case a new connection is created every time, or to create one connection and re-use that. 

So if `Database` was able to automatically re-use a finite amount of connections to improve performance that would be a win win.

**Comment by collinhundley** [comment]
That sounds like a good idea. I'm no connection-pooling expert, but we'll need a way to catch dropped connections and recycle them somehow. There's a variety of reasons a request could fail, so we'll probably need to create a new connection and retry the request on the new one.

**Comment by Mordil** [comment]
@collinhundley Why was this issue closed if there seems to be a desire for the feature?

Should a new issue be created proposing the feature before implementing?
