### ISSUE TITLE
Mapping Integer and Double values to TIMESTAMP fields on DB

### ISSUE THREAD

**Issue by eneko** [vapor/mysql#53]
When using `Int` or `Double` on `makeNode()` for a date field inside a Fluent Model, MySQL fails to map the value to a TIMESTAMP field.

Source code example (`Double`):

``` swift
struct Location: Model {
    var id: Node?
    var createdAt: Date

    func makeNode(context: Context) throws -> Node {
        return try Node(node: [
            "id": id,
            "created_at": createdAt.timeIntervalSince1970  // NSTimeInterval == Double
        ])
}
```

Source code example (`Int`):

``` swift
struct Location: Model {
    var id: Node?
    var createdAt: Date

    func makeNode(context: Context) throws -> Node {
        return try Node(node: [
            "id": id,
            "created_at": Int(createdAt.timeIntervalSince1970)  // Int
        ])
}
```

Error response:

```
[to be updated]
```

**Comment by hhanesand** [comment]
@eneko Any update on this?

**Comment by eneko** [comment]
@hhanesand not so far, never managed to add the Date to TIMESTAMP field conversion (and viceversa).

Furthermore, MySQL date fields are returned as an ISO string, so they can be converted to a Date using a DateFormatter. However, I found issues using DateFormatters on Linux so I am using Ints and handling dates as unix timestamps (which works well for me but might not work for everyone).

**Comment by BrettRToomey** [comment]
MySQL now has `Date(mysql: mysqlFormattedString)` and `Date().mysql` for serialization and deserialization. I've been working on `Date` serialization and deserialization with `Node`. Will post a reference here when it's merged, but going to close this for now.
