### ISSUE TITLE
Foreign Keys between tables

### ISSUE THREAD

**Issue by hhanesand** [vapor/mysql#56]
When preparing schemas with relations to other tables through the `prepare` function on the `Preparation` protocol, foreign key relations do not seem to be created in the database, even if the `parent` method on `Schema` is used.

For example, for the following schema (specifically the `review` table),
![screen shot 2016-10-03 at 3 15 26 pm](https://cloud.githubusercontent.com/assets/3051243/19056151/43534f2c-897c-11e6-987c-84f94371a066.png)
created with the following code,
```swift
static func prepare(_ database: Database) throws {
        try database.create(self.entity, closure: { box in
            box.id()
            box.string("description")
            box.string("rating")
            box.string("date")
            box.parent(Box.self, optional: false)
            box.parent(User.self, optional: false)
        })
    }
```
one would expect that foreign key relations should be created within the database. However, none seem to be created. I'm certainly no expert when it comes to MySQL databases, so I do not know if this is a big problem or not, but I just wanted to check in with you guys to see if this was an issue.

P.S. For clarification, generating code that looks something like this
```mysql
CONSTRAINT `fk_review_box1`
    FOREIGN KEY (`box_id` , `box_vendor_id`)
    REFERENCES `mydb`.`box` (`id` , `vendor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
```
would create the missing link that I was talking about above.

**Comment by collinhundley** [comment]
Hi @hhanesand, it looks like your questions is specifically about the [Fluent ORM](https://github.com/vapor/fluent). Since the issue doesn't appear to be related to the MySQL driver itself, I'd recommend that you post your question in that repo to get better help.

**Comment by hhanesand** [comment]
Thank you, I will move it there.
