### ISSUE TITLE
Support SMALLINT as well / unsigned functionality seems not to work at all

### ISSUE THREAD

**Issue by popaaaandrei** [vapor/mysql#57]
Hey guys, 

I get a lot of `[MySQL] Unsupported type: SMALLINT` errors.

MySQL `SMALLINT` => C API `MYSQL_TYPE_SHORT` => C `short int` (16 bit) => Swift `UInt16 / Int16`.

Something like this in Bind+Node.swift solves my problem.

```
case MYSQL_TYPE_SHORT:
                if cBind.is_unsigned == 1 {
                    let uint = unwrap(buffer, UInt16.self)
                    return .number(.uint(UInt(uint)))
                } else {
                    let int = unwrap(buffer, Int16.self)
                    return .number(.int(Int(int)))
                }
```

On the other hand, unsigned functionality seems not to work at all. I have a lot of unsigned types in my database but `cBind.is_unsigned = 0` always, as the initializer always sets `unsigned: Bool = false`. This result in a proper database structure being unusable at all. 

Thank you,
Andrei

**Comment by BrettRToomey** [comment]
As far as I can tell, the unsigned functionality seems to be fixed, but `SMALLINT` support still isn't added. @tannernelson Is `SMALLINT` worth supporting? If so, we should probably open another issue for it or trim the unsigned stuff from the OP.

**Comment by florianreinhart** [comment]
I need support for SMALLINT. Do you have any plans to add support for it?
