### ISSUE TITLE
Not recovering from timeout

### ISSUE THREAD

**Issue by BrettRToomey** [vapor/mysql#60]
By default, MySQL times out a connection that has been idle for more than 8 hours. Presently, `vapor/mysql` isn't recovering from this timeout and opening a new connection with the server, thusly causing an error to be thrown on the next query.

**Comment by collinhundley** [comment]
@BrettRToomey Check out the `connection-pool` branch. It maintains a pool of connections and automatically recovers from timeouts. We were waiting to pull it into master after v1.0, so it's probably a good time to revisit this.

If someone wants to do more testing, that would be great. FWIW I have 2 live servers that have been running on the `connection-pool` branch without a hiccup for about 3 weeks.

**Comment by tannernelson** [comment]
Fixed in MySQL Driver 1.0.1 https://github.com/vapor/mysql-driver/releases/tag/1.0.1
