### ISSUE TITLE
crush when i do this .execute("START TRANSCATION;", [], connection)

### ISSUE THREAD

**Issue by carlhung** [vapor/mysql#73]
I am using Mac.
when i run this line,
.execute("START TRANSCATION;", [], connection)
it crushes, and found this error,
error: MySQL.Error.prepare("This command is not supported in the prepared statement protocol yet")
i have no idea why it would throw.
without this line, it won't throw. but i need this line to guarantee that upcoming commands work together. 
Is it possible to fix that?
Thanks.

**Comment by tannernelson** [comment]
Looks like MySQL prepared statements do not support transaction queries. There is no way to perform non prepared statement queries with this module currently. That functionality will need to be added.

Possibly we could switch to prepared statements if and only if there are variables to be parameterized.

**Comment by BrettRToomey** [comment]
@carlhung There's now a transaction function on `Connection`. Adding support for prepared statements is definitely its own issue and one I'm not sure we have a direct answer to. Closing this for now.
