### ISSUE TITLE
Poor query performance with large result sets

### ISSUE THREAD

**Issue by vzsg** [vapor/mysql#80]
Consider the simplest and most naive of the database queries, where `thing` is a table with two `varchar(255)` columns and 50000 rows of fake data:

```
let db = try Database(host: "127.0.0.1",
                      user: "root",
                      password: "",
                      database: "test")

let result = try db.execute("SELECT * FROM thing")
```

Running this query takes more than 2 seconds in a debug build, little more than 1 second in a release build on a 2015 MBP. The numbers are striking, the query is an order of magnitude slower than the time needed for the actual SQL fetch! (Tested by commenting out the [parsing code](https://github.com/vapor/mysql/blob/master/Sources/MySQL/Connection.swift#L139-L152) from Connection).

---

After playing around with Instruments, I found a few bottlenecks:

- [x] The field names are converted from C to Swift strings for every row (see #79 for the fix; ~40% time reduction)
- [x] Decoding strings [byte-by-byte](https://github.com/vapor/mysql/blob/master/Sources/MySQL/Bind%2BNode.swift#L136) takes most of the time (see next section)
- [x] Creating a new dictionary for every row causes unnecessary allocations [here](https://github.com/vapor/mysql/blob/master/Sources/MySQL/Connection.swift#L139) (see #81; ~5% reduction)
- [ ] Hashing strings to build a dictionary is slow (which probably cannot be helped...)

---

I spent a few waking hours trying to replace the UTF8 decoding code, without a viable result.

Using the `String(bytes:encoding:)` initializer on the buffer (just like in the [Postgres](https://github.com/vapor/postgresql/blob/master/Sources/PostgreSQL/PostgresBinaryUtils.swift#L154) driver) gave me blazing fast results(*), but the whole result set was leaked, despite the fact that no native memory should be retained by the pointer operations. To reproduce, replace [these lines](https://github.com/vapor/mysql/blob/master/Sources/MySQL/Bind%2BNode.swift#L68-L72) with the Postgres decoding code.

(*) In terms of running time, fixing this would grant a tolerable result, only 3 times slower than the raw fetch.

Any insight is welcome.

**Comment by vzsg** [comment]
Further experiments show that replacing the byte-decoded UInt8 sequence -> String conversion with `String(validatingUTF8:)` brings up the speed to a tolerable level while reducing memory usage.

Unfortunately, one cannot assume with MySQL that the data doesn't contain ASCII NULLs inside, so it's not a viable solution...

**Comment by hhanesand** [comment]
@vzsg I'd like to investigate this, but how do I go about verifying if the result set is leaked or not?

**Comment by vzsg** [comment]
I was using Xcode's Debug Navigator for tracking total memory use – if it's not a flat graph, something is wrong – then Memory Graph and Instruments to look into what's leaking.

**Comment by BrettRToomey** [comment]
Any updates on this?

**Comment by hhanesand** [comment]
No, I haven't gotten to this. Thinking we should revisit this after 2.0 comes out of beta

**Comment by tanner0101** [comment]
We've moved to a much more efficient `makeString()` implementation in Vapor 2. https://github.com/vapor/bits/blob/master/Sources/Bits/ByteSequence%2BConversions.swift#L4-L10.

Going to close this issue for now since a good portion of it has been addressed and the issue of performance is pretty general. Please feel free to open a new issue for any specific performance issues.

**Comment by vzsg** [comment]
I might do a stress test again later, but I'm sure the situation is already far improved since January.
