### ISSUE TITLE
How to skip ssl when establish connection

### ISSUE THREAD

**Issue by xiongyuxi** [vapor/mysql#82]
Hi,
I had a database server with mysql5.6. When I try to connect to DB I have this issue.
ERROR 2026 (HY000): SSL connection error: error:00000001:lib(0):func(0):reason(1)
How can I skip ssl connection or is there a way to add ssl certification?
Thanks!

**Comment by tanner0101** [comment]
Fluent 3 now longer uses the libmysql library. SSL will be implemented soon and it will support using a plaintext connection 👍
