### ISSUE TITLE
BLOB type should map to Node.bytes, not Node.string

### ISSUE THREAD

**Issue by vzsg** [vapor/mysql#83]
Currently the BLOB column type goes through the same UTF-8 decoding as string types, despite the common definition (incl. [MySQL's own](https://dev.mysql.com/doc/refman/5.7/en/blob.html)) that BLOB (and BINARY and VARBINARY) columns store raw binary data.

I think this type should be mapped to `Node.bytes(Bytes)` directly, without any encoding in either direction.

**Comment by tannernelson** [comment]
@vzsg totally agree. I'm excited about the performance improvements the new `bytes` case is going to get us.
