### ISSUE TITLE
Stored procedure not returning any results.

### ISSUE THREAD

**Issue by kapsy** [vapor/mysql#87]
I've been successfully using vapor/mysql for standard calls, for example:
`let result = try database.execute("SELECT * FROM customers;")`

But when I try a stored procedure that does the exact same thing:
`let result = try database.execute("CALL selectCustomers();")`
The result dictionary is empty.

I can confirm that the procedure works when calling directly from mysql.

Here is the stored procedure:
```
DROP PROCEDURE IF EXISTS getAllCustomers;
DELIMITER //
CREATE PROCEDURE getAllCustomers()
BEGIN
    SELECT * FROM customers;
END //
DELIMITER ;
```

I'm not sure if this is a bug, or is it that vapor/mysql does not support stored procedures? Any help much appreciated.

**Comment by kapsy** [comment]
I've also tried passing the flag `CLIENT_MULTI_STATEMENTS` as suggested for when calling `mysql_real_connect()` for the MySQL C API. I tried passing the flag through vapor/mysql: 
```
import CMySQLMac
myDatabase = try MySQL.Database(host: "127.0.0.1", user: "usr", password: "pw", database: "db", flag: CLIENT_MULTI_STATEMENTS)
```
This passed the flag to `my_sql_connect()` ok, but still did not return the results of the procedure.

**Comment by vzsg** [comment]
I'm afraid it's not supported currently as the driver executes every query using prepared statements.

Reading the results of a CALL statement requires [special handling](https://dev.mysql.com/doc/refman/5.7/en/c-api-prepared-call-statements.html), while the current implementation only does a single bind-fetch trip.

**Comment by LoganWright** [comment]
@kapsy @vzsg what would it take to support this as an additional feature? I'd imagine procedures to be a nice addition if we could work it.

**Comment by vzsg** [comment]
I'm not quite sure why the example above didn't work, actually. The first result set should have been returned, even if the driver doesn't read until the final packet.

I think the driver could follow the [example](https://dev.mysql.com/doc/refman/5.7/en/c-api-prepared-call-statements.html) using a `repeat-while` loop, and build an `.array` Node where every child is an object built from the result set (just like the current output).

**Comment by kapsy** [comment]
@vzsg Ok I see - thanks v. much for your response. @LoganWright support for stored procedures would be very welcome.

**Comment by vzsg** [comment]
Okay, fun fact time: `mysql_stmt_result_metadata(statement)` cannot return anything before executing the stored procedure, this is why the driver discards the results right away.

I wonder if there is a disadvantage in executing a statement first and getting metadata later.

**Comment by gonzalo-aizpun-umewin** [comment]
> _support for stored procedures would be very welcome._

👍

**Comment by tanner0101** [comment]
Version 3.0 of the driver adds support for prepared statements and "administrative queries" as it's called. You should be able to select data from stored procedure just fine using the latter type of query going forward.
