### ISSUE TITLE
swift-package: error: unsatisfiable with version 2

### ISSUE THREAD

**Issue by russanto** [vapor/mysql#96]
Hi, I'm trying to work with Vapor MySQL and Kitura but I always get the error in the title when I run swift build or swift package generate-xcodeproj. It only happens with new version 2, I works perfectly with latest version 1. Here is my Package.swift
```
let package = Package(
  name: "Kitura-Starter",
  targets: [
    Target(name: "Kitura-Starter",
           dependencies: [.Target(name: "Controller")]),
    Target(name: "Controller")
  ],
  dependencies: [
    .Package(url: "https://github.com/IBM-Swift/Kitura.git", majorVersion: 1, minor: 7),
    .Package(url: "https://github.com/IBM-Swift/HeliumLogger.git", majorVersion: 1, minor: 7),
    .Package(url: "https://github.com/IBM-Swift/Kitura-Credentials", majorVersion: 1, minor: 7),
    .Package(url: "https://github.com/IBM-Bluemix/cf-deployment-tracker-client-swift.git", majorVersion: 3),
    .Package(url: "https://github.com/IBM-Swift/BlueCryptor.git", majorVersion: 0, minor: 8),
    .Package(url: "https://github.com/vapor/mysql.git", majorVersion: 2)
])
```

**Comment by vzsg** [comment]
I copied your dependencies into a new project and it resolved just fine. Perhaps you have a `Package.pins` file lying around from an older build? Try removing that along with the `.build` folder and building again.

**Comment by russanto** [comment]
OK, it worked for me tu delete `Package.pins` and `.build` folder but now, I'm working on Ubuntu, it require a cmysql package that it can't find and I don't know where to search for.
`cmysql libcurl4-openssl-dev openssl libssl-dev`
`E: Unable to locate package cmysql`

**Comment by vzsg** [comment]
The `cmysql` package is available in Vapor's own APT repository. See the [documentation](https://docs.vapor.codes/2.0/getting-started/install-on-ubuntu/).
