### ISSUE TITLE
Cannot invoke 'Database' with an argument list of type '(host: String, user: String, password: String, database: String)'

### ISSUE THREAD

**Issue by O-mkar** [vapor/mysql#99]
I have migrated my code to Vapor 2.0 and i'm facing this error
**Cannot invoke 'Database' with an argument list of type '(host: String, user: String, password: String, database: String)'**

```
extension MySQL.Database {
    static func makeConnection() -> MySQL.Database {
        do {
            let mysql = try MySQL.Database(
                host: "127.0.0.1",
                user: "root",
                password: "",
                database: "Radar"
            )
            try mysql.execute("SELECT @@version")
            return mysql
        } catch {

            fatalError("MySQL Error")
        }
    }
}

```
<img width="1188" alt="screen shot 2017-06-16 at 3 57 38 pm" src="https://user-images.githubusercontent.com/16367429/27223115-cc72475a-52ac-11e7-8531-9dbc17b8889a.png">

**Comment by 0xTim** [comment]
@O-mkar `host` has been renamed to `hostname`. This should fix the compiler error
